<a href="https://colab.research.google.com/github/Sakthipooja47/tasks/blob/main/intern2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/Dataset .csv")
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [ ]:
numerical_summary=df.describe()

In [ ]:
numerical_df = df.select_dtypes(include=np.number)

In [ ]:
numerical_summary.loc['mean']=numerical_df.mean()

In [ ]:
numerical_summary.loc['median']=numerical_df.median()

In [ ]:
numerical_summary.loc['std']=numerical_df.std()

In [ ]:
print("Numerical Summary:")
print(numerical_summary)

Numerical Summary:
        Restaurant ID  Country Code    Longitude     Latitude  \
count    9.551000e+03   9551.000000  9551.000000  9551.000000
mean     9.051128e+06     18.365616    64.126574    25.854381
std      8.791521e+06     56.750546    41.467058    11.007935
min      5.300000e+01      1.000000  -157.948486   -41.330428
25%      3.019625e+05      1.000000    77.081343    28.478713
50%      6.004089e+06      1.000000    77.191964    28.570469
75%      1.835229e+07      1.000000    77.282006    28.642758
max      1.850065e+07    216.000000   174.832089    55.976980
median   6.004089e+06      1.000000    77.191964    28.570469

        Average Cost for two  Price range  Aggregate rating         Votes
count            9551.000000  9551.000000       9551.000000   9551.000000
mean             1199.210763     1.804837          2.666370    156.909748
std             16121.183073     0.905609          1.516378    430.169145
min                 0.000000     1.000000          0.000000      0.000000
25%               250.000000     1.000000          2.500000      5.000000
50%               400.000000     2.000000          3.200000     31.000000
75%               700.000000     2.000000          3.700000    131.000000
max            800000.000000     4.000000          4.900000  10934.000000
median            400.000000     2.000000          3.200000     31.000000

In [ ]:
categorical_columns=['Country Code','City','Cuisines']
for col in categorical_columns:
  print(f"\nDistribution of {col}:")
  print(df[col].value_counts())

Distribution of Country Code:
Country Code
1      8652
216     434
215      80
30       60
214      60
189      60
148      40
208      34
14       24
162      22
94       21
184      20
166      20
191      20
37        4
Name: count, dtype: int64

Distribution of City:
City
New Delhi           5473
Gurgaon             1118
Noida               1080
Faridabad            251
Ghaziabad             25
                    ...
Panchkula              1
Mc Millan              1
Mayfield               1
Macedon                1
Vineland Station       1
Name: count, Length: 141, dtype: int64

Distribution of Cuisines:
Cuisines
North Indian                                             936
North Indian, Chinese                                    511
Chinese                                                  354
Fast Food                                                354
North Indian, Mughlai                                    334
                                                        ...
Bengali, Fast Food                                         1
North Indian, Rajasthani, Asian                            1
Chinese, Thai, Malaysian, Indonesian                       1
Bakery, Desserts, North Indian, Bengali, South Indian      1
Italian, World Cuisine                                     1
Name: count, Length: 1825, dtype: int64

In [ ]:
top_cuisines=df['Cuisines'].value_counts().head(10)
top_cities=df['City'].value_counts().head(10)

In [ ]:
print("\nTop 10 Cuisines:")
print(top_cuisines)

Top 10 Cuisines:
Cuisines
North Indian                      936
North Indian, Chinese             511
Chinese                           354
Fast Food                         354
North Indian, Mughlai             334
Cafe                              299
Bakery                            218
North Indian, Mughlai, Chinese    197
Bakery, Desserts                  170
Street Food                       149
Name: count, dtype: int64

In [ ]:
print("\nTop 10 Cities with Highest Number of Restaurents:")
print(top_cities)

Top 10 Cities with Highest Number of Restaurents:
City
New Delhi       5473
Gurgaon         1118
Noida           1080
Faridabad        251
Ghaziabad         25
Bhubaneshwar      21
Amritsar          21
Ahmedabad         21
Lucknow           21
Guwahati          21
Name: count, dtype: int64